[package]
name = "oxidemu"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "common" }
chip8 = { path = "chip8" }
ui = { path = "ui" }

# set env var RUSTFLAGS='-L path/to/dir/SDL.lib' before build