[package]
name = "ui"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.18.0"
egui = "0.18.1"
egui_glow = { version="0.18.1", features=["winit"] }
glutin = "0.28.0"
glow = "0.11.2"
gilrs = "0.8.1"
winit = "0.26.1"

common = { path = "../common" }
chip8 = { path = "../chip8" }

[features]
default = []
persistence = ["eframe/persistence"]

[dependencies.sdl2]
features = ["unsafe_textures"]
version = "0.35.2"
default-features = false
