[package]
name = "ui"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.17.0"
egui = "0.17.0"
egui_glow = "0.17.0"
glow = "0.11"
epaint = "0.17.0"
sdl2 = "0.35.2"
common = { path = "../common" }
chip8 = { path = "../chip8" }

[features]
default = []
persistence = ["eframe/persistence"]